### PR TITLE
Used DML commands

### PR DESCRIPTION
**Pull request by Akanksha987**
#MileStone 3
->Used three DML commands for the next milestone. 
->Self viva is here.
[Link 1](https://www.loom.com/share/dc538baea7dc47e597f80db160799dbb?sid=6e7fad8f-b479-4a76-bd2e-969889e01ff7)
[Link 2](https://www.loom.com/share/0f6111f88359433e8ce85885725c4062?sid=7aa76e6d-7d93-43c4-a278-a31b0dcc5a7c)

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
Hey @Akanksha987 ,
Your explanation is good and sufficient for all DML commands.
But Delete command and its execution are missing,

You can merge it for DML.

If you wish to score fully, you can add and submit another video explaining the missed one as mentioned above.

**Comment by Akanksha987** [comment]
Okay, I will submit it by today

**Comment by Akanksha987** [comment]
Hey @PRASANNAPATHI here is the [link](https://www.loom.com/share/8b302952c0db4c04a44ec24ce47e388a?sid=10ffd2bb-bda5-4a32-b1a7-66260d9a675d) for delete command explanation and I had also updated the code

**Comment by PRASANNAPATHI** [comment]
Yes @Akanksha987 , 
Now everything is fine.

Please merge it for DML.

**Pull request merged**
